// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Read env and normalize
let SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL || '').trim();
let SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '').trim();

// Optional fallback: allow providing project ref and build the full URL
const PROJECT_REF = (import.meta.env.VITE_SUPABASE_PROJECT_REF || '').trim();
if (!SUPABASE_URL && PROJECT_REF) {
  SUPABASE_URL = `https://${PROJECT_REF}.supabase.co`;
}

// Guardrails: common misconfigurations
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('[Supabase] Missing configuration. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in .env');
}
if (SUPABASE_URL.includes('api.supabase.com')) {
  console.error('[Supabase] Invalid URL detected: api.supabase.com is not your project URL. Use https://<project-ref>.supabase.co');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});